### Register User
POST https://salmaparadisa-production.up.railway.app/api/auth/register
Content-Type: application/json

{
  "username": "user1",
  "password": "password1",
  "role": "user"
}

### Register Admin
POST https://salmaparadisa-production.up.railway.app/api/auth/register
Content-Type: application/json

{
  "username": "admin1",
  "password": "password1",
  "role": "admin"
}

### Login User
POST https://salmaparadisa-production.up.railway.app/api/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

### Login Admin
POST https://salmaparadisa-production.up.railway.app/api/auth/login
Content-Type: application/json

{
  "username": "admin1",
  "password": "password1"
}
